# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.srcs/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/design_1_doug_custom_0_0.xci
# IP: The module: 'design_1_doug_custom_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/radio_subIP_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radio_subIP_0 || ORIG_REF_NAME==radio_subIP_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlslice_1_1/design_1_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_1 || ORIG_REF_NAME==design_1_xlslice_1_1} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlslice_1_0/design_1_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_0 || ORIG_REF_NAME==design_1_xlslice_1_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_slicecomplex_imag_0/design_1_slicecomplex_imag_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_slicecomplex_imag_0 || ORIG_REF_NAME==design_1_slicecomplex_imag_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlslice_2_2/design_1_xlslice_2_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_2_2 || ORIG_REF_NAME==design_1_xlslice_2_2} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_1_1/design_1_fir_compiler_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_1_1 || ORIG_REF_NAME==design_1_fir_compiler_1_1} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_1_0/design_1_fir_compiler_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_1_0 || ORIG_REF_NAME==design_1_fir_compiler_1_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_0_1/design_1_fir_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_1 || ORIG_REF_NAME==design_1_fir_compiler_0_1} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_0_0/design_1_fir_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_0 || ORIG_REF_NAME==design_1_fir_compiler_0_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_dds_compiler_1/design_1_dds_compiler_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dds_compiler_1 || ORIG_REF_NAME==design_1_dds_compiler_1} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_dds_compiler_0_0/design_1_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dds_compiler_0_0 || ORIG_REF_NAME==design_1_dds_compiler_0_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_cmpy_0_0/design_1_cmpy_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cmpy_0_0 || ORIG_REF_NAME==design_1_cmpy_0_0} -quiet] -quiet

# XDC: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_1_1/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_1_1 || ORIG_REF_NAME==design_1_fir_compiler_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_1_0 || ORIG_REF_NAME==design_1_fir_compiler_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_0_1/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_1 || ORIG_REF_NAME==design_1_fir_compiler_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_0 || ORIG_REF_NAME==design_1_fir_compiler_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_ooc.xdc

# IP: D:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.srcs/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/design_1_doug_custom_0_0.xci
# IP: The module: 'design_1_doug_custom_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/radio_subIP_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==radio_subIP_0 || ORIG_REF_NAME==radio_subIP_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlslice_1_1/design_1_xlslice_1_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_1 || ORIG_REF_NAME==design_1_xlslice_1_1} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlslice_1_0/design_1_xlslice_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_0 || ORIG_REF_NAME==design_1_xlslice_1_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_slicecomplex_imag_0/design_1_slicecomplex_imag_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_slicecomplex_imag_0 || ORIG_REF_NAME==design_1_slicecomplex_imag_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_xlslice_2_2/design_1_xlslice_2_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_2_2 || ORIG_REF_NAME==design_1_xlslice_2_2} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_1_1/design_1_fir_compiler_1_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_1_1 || ORIG_REF_NAME==design_1_fir_compiler_1_1} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_1_0/design_1_fir_compiler_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_1_0 || ORIG_REF_NAME==design_1_fir_compiler_1_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_0_1/design_1_fir_compiler_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_1 || ORIG_REF_NAME==design_1_fir_compiler_0_1} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_0_0/design_1_fir_compiler_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_0 || ORIG_REF_NAME==design_1_fir_compiler_0_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_dds_compiler_1/design_1_dds_compiler_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dds_compiler_1 || ORIG_REF_NAME==design_1_dds_compiler_1} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_dds_compiler_0_0/design_1_dds_compiler_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dds_compiler_0_0 || ORIG_REF_NAME==design_1_dds_compiler_0_0} -quiet] -quiet

# IP: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_cmpy_0_0/design_1_cmpy_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cmpy_0_0 || ORIG_REF_NAME==design_1_cmpy_0_0} -quiet] -quiet

# XDC: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_1_1/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_1_1 || ORIG_REF_NAME==design_1_fir_compiler_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_1_0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_1_0 || ORIG_REF_NAME==design_1_fir_compiler_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_0_1/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_1 || ORIG_REF_NAME==design_1_fir_compiler_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_fir_compiler_0_0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_fir_compiler_0_0 || ORIG_REF_NAME==design_1_fir_compiler_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/School/sysFPGAlab/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_doug_custom_0_0/src/radio_subIP_0_1/src/design_1_ooc.xdc
